#pragma once

#define SOLVER_ITERATIONS 20


#define FALSE	0
#define TRUE	1

#define DEBUG_PHYSICS TRUE

#define DEBUGDRAW_CONSTRAINTS			TRUE
#define DEBUGDRAW_MANIFOLDS				TRUE
#define DEBUGDRAW_COLLISIONVOLUMES		TRUE
#define DEBUGDRAW_SPACEPARTITION		TRUE

#define PHYSICS_UPDATE_THREADS 2
#define NARROWPHASE_THREADS 3
#define PRESOLVER_THREADS 2